substitutions:
  _PROXY_URL: 'http://10.0.0.2:3128'
  _SOCKS5_PROXY: '10.0.0.2 1080'
  _VERSION: 'latest'
  _IMAGE_NAME: 'europe-west1-docker.pkg.dev/${_PROJECT_ID}/backend/api'
  _TAG: 'latest'
  _SUPABASE_VERSION: '1.200.0'

steps:
  # ---------------------------------------------------------
  # Step 1: Database Migration (Proxy Tunnel)
  # ---------------------------------------------------------
  - name: 'node:20-bookworm-slim'
    id: 'db-migration'
    entrypoint: 'bash'
    secretEnv: ['DOPPLER_SECRETS_JSON']
    env:
      - 'PROXY_URL=${_PROXY_URL}'
      - 'SOCKS5_PROXY=${_SOCKS5_PROXY}'
      - 'SUPABASE_VERSION=${_SUPABASE_VERSION}'
    args:
      - '-c'
      - |
        set -e
        export http_proxy=$$PROXY_URL
        export https_proxy=$$PROXY_URL

        echo "🔧 Installing utilities..."
        apt-get update -qq && apt-get install -y -qq socat curl > /dev/null

        echo "📥 Downloading Supabase CLI..."
        curl -fSL "https://github.com/supabase/cli/releases/download/v${_SUPABASE_VERSION}/supabase_linux_amd64.tar.gz" -o supabase.tar.gz
        tar -xzf supabase.tar.gz -C /usr/local/bin
        chmod +x /usr/local/bin/supabase

        echo "🔌 Setting up Proxy Tunnel..."
        
        # 2. Robust Parsing Logic (Fixes the "3 parameters required" error)
        eval $(node -e '
          try {
            const secrets = JSON.parse(process.env.DOPPLER_SECRETS_JSON);
            const dbUrl = secrets.DIRECT_DB_CONNECTION_STRING;
            
            // CLEAN THE PROXY STRING
            // Handles "10.0.0.2 1080", "10.0.0.2:1080", and "socks5://10.0.0.2:1080"
            let proxyRaw = process.env.SOCKS5_PROXY || "";
            proxyRaw = proxyRaw.replace(/^(socks5:\/\/|http:\/\/)/, ""); // Remove scheme
            proxyRaw = proxyRaw.replace(/:/g, " "); // Replace colons with spaces
            
            const proxyParts = proxyRaw.split(" ").filter(Boolean); // Split and remove empty
            const proxyIp = proxyParts[0];
            const proxyPort = proxyParts[1] || "1080";

            if (!proxyIp) throw new Error("Could not extract Proxy IP");

            // Extract DB Host and Port
            const match = dbUrl.match(/@([^/:]+):?(\d+)?\//);
            if (!match) throw new Error("Could not parse DB Host/Port");

            const remoteHost = match[1];
            const remotePort = match[2] || "5432";
            const localUrl = dbUrl.replace(remoteHost, "127.0.0.1").replace(":" + remotePort, ":5432");

            console.log(`export PROXY_IP=${proxyIp}`);
            console.log(`export PROXY_PORT=${proxyPort}`);
            console.log(`export TARGET_HOST=${remoteHost}`);
            console.log(`export TARGET_PORT=${remotePort}`);
            console.log(`export LOCAL_DB_URL="${localUrl}"`);
          } catch(e) { console.error(e); process.exit(1); }
        ')

        echo "Target: $$TARGET_HOST:$$TARGET_PORT via Proxy: $$PROXY_IP:$$PROXY_PORT"

        # 3. Start Tunnel (SOCKS4A)
        # SOCKS4A:<proxy-ip>:<target-host>:<target-port>
        socat TCP4-LISTEN:5432,fork,bind=127.0.0.1 SOCKS4A:$$PROXY_IP:$$TARGET_HOST:$$TARGET_PORT,socksport=$$PROXY_PORT &
        SOCAT_PID=$$!
        
        sleep 3

        echo "🚀 Running Supabase Migration..."
        supabase db push --db-url "$$LOCAL_DB_URL"

        # Cleanup
        kill $$SOCAT_PID

  # ---------------------------------------------------------
  # Step 2: Build Application
  # ---------------------------------------------------------
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://./backend'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:${_VERSION}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--build-arg=PRODUCTION=true'
      - '--cache=true'

availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/doppler-hit8-prod/versions/latest
    env: 'DOPPLER_SECRETS_JSON'

options:
  pool:
    name: 'projects/${_PROJECT_ID}/locations/europe-west1/workerPools/private-pool-1'
