steps:
  # Database Migration
  # We use a standard Debian image instead of Alpine because proxychains + dynamic linking works better
  - name: 'debian:bookworm-slim'
    id: 'db-migration'
    entrypoint: 'bash'
    env:
      - 'PROXY_URL=http://10.0.0.2:3128'
      - 'SOCKS5_PROXY=10.0.0.2 1080'
    secretEnv: ['DOPPLER_SECRETS_JSON']
    args:
      - '-c'
      - |
        set -e

        echo "âš™ï¸  Configuring environment..."
        export http_proxy=$$PROXY_URL
        export https_proxy=$$PROXY_URL
        
        # 1. Install dependencies (curl, nodejs for parsing, proxychains, ca-certificates)
        apt-get update -qq && apt-get install -y -qq curl nodejs proxychains4 ca-certificates > /dev/null

        # 2. Install Supabase CLI (Use official script, it handles arch/version)
        # We pipe to bash but ensure proxy env vars are set first
        curl -fsSL https://raw.githubusercontent.com/supabase/cli/main/install.sh | bash

        # 3. Configure Proxychains (Simple one-liner)
        # "quiet_mode" hides the endless 'S-chain' logs
        echo -e "strict_chain\nproxy_dns\nremote_dns_subnet 224\ntcp_read_time_out 15000\ntcp_connect_time_out 8000\n[ProxyList]\nsocks5 $$SOCKS5_PROXY" > /etc/proxychains4.conf

        # 4. Extract Connection String
        DB_URL=$(node -e 'try { console.log(JSON.parse(process.env.DOPPLER_SECRETS_JSON).DIRECT_DB_CONNECTION_STRING) } catch(e) { process.exit(1) }')

        # 5. Run Migration
        echo "ðŸš€ Running migration..."
        # We force proxychains to route the Go binary's TCP connections
        proxychains4 -q supabase db push --db-url "$$DB_URL"

  # Build and Push Docker Image (Kaniko)
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://./backend'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:${_VERSION}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--build-arg=PRODUCTION=true'
      - '--cache=true'
      - '--cache-ttl=24h'

availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/doppler-hit8-prod/versions/latest
    env: 'DOPPLER_SECRETS_JSON'

options:
  pool:
    name: 'projects/${_PROJECT_ID}/locations/europe-west1/workerPools/private-pool-1'
