steps:
  # Database Migration
  - name: 'node:20-alpine'
    id: 'db-migration'
    entrypoint: 'sh'
    env:
      # HTTP proxy for HTTP/HTTPS traffic (Squid)
      - 'PROXY_URL=http://10.0.0.2:3128'
      # SOCKS5 proxy for TCP traffic like PostgreSQL (Dante)
      - 'SOCKS5_PROXY=socks5://10.0.0.2:1080'
    args:
      - '-c'
      - |
        set -e
        echo "⚙️ Configuring Proxy..."
        export http_proxy=$$PROXY_URL
        export https_proxy=$$PROXY_URL
        
        echo "📦 Installing wget and downloading Supabase CLI binary..."
        apk add --no-cache wget >/dev/null 2>&1 || echo "⚠️  wget may already be installed"
        
        ARCH=$$(uname -m | sed 's/x86_64/amd64/')
        wget -q "https://github.com/supabase/cli/releases/latest/download/supabase_linux_$${ARCH}.tar.gz" -O /tmp/supabase.tar.gz || {
          echo "❌ Failed to download Supabase CLI binary"
          exit 1
        }
        
        tar -xzf /tmp/supabase.tar.gz -C /usr/local/bin
        chmod +x /usr/local/bin/supabase
        
        echo "🔑 Extracting connection string from secrets..."
        DIRECT_DB_CONNECTION_STRING=$$(node -e 'try { console.log(JSON.parse(process.env.DOPPLER_SECRETS_JSON).DIRECT_DB_CONNECTION_STRING) } catch(e) { console.error("JSON parse error:", e.message); process.exit(1); }') || {
          echo "❌ Failed to parse secrets JSON"
          exit 1
        }
        
        if [ -z "$$DIRECT_DB_CONNECTION_STRING" ]; then
           echo "❌ Error: DIRECT_DB_CONNECTION_STRING not found in secrets."
           exit 1
        fi

        echo "🚀 Running database migration through SOCKS5 proxy..."
        # Use proxychains or similar to route PostgreSQL through SOCKS5 proxy
        # Install proxychains for SOCKS5 support
        apk add --no-cache proxychains-ng >/dev/null 2>&1 || echo "⚠️  proxychains may already be installed"
        
        # Configure proxychains to use SOCKS5 proxy
        PROXY_HOST=$$(echo "$$SOCKS5_PROXY" | sed 's|socks5://||' | cut -d: -f1)
        PROXY_PORT=$$(echo "$$SOCKS5_PROXY" | sed 's|socks5://||' | cut -d: -f2)
        echo "socks5 $$PROXY_HOST $$PROXY_PORT" > /etc/proxychains.conf
        echo "strict_chain" >> /etc/proxychains.conf
        echo "proxy_dns" >> /etc/proxychains.conf
        
        # Run migration through proxychains
        proxychains4 -q supabase db push --db-url "$$DIRECT_DB_CONNECTION_STRING" --debug || {
          echo "❌ Migration failed"
          exit 1
        }
        
        echo "✅ Migration completed successfully"
    
    secretEnv: ['DOPPLER_SECRETS_JSON']

  # Build and Push Docker Image
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://./backend'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:${_VERSION}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--build-arg=PRODUCTION=true'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--cache-repo=gcr.io/${_PROJECT_ID}/cache'

# Secrets Configuration
availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/doppler-hit8-prod/versions/latest
    env: 'DOPPLER_SECRETS_JSON'

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/${_PROJECT_ID}/locations/europe-west1/workerPools/private-pool-1'
