steps:
  # -------------------------------------------------------------------------
  # 1. Database Migration (Install CLI on the fly)
  # -------------------------------------------------------------------------
  - name: 'node:20-bullseye-slim'
    id: 'db-migration'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        npm install -g supabase
        
        # Extract DIRECT_DB_CONNECTION_STRING from JSON secret
        DIRECT_DB_CONNECTION_STRING=$$(node -e "console.log(JSON.parse(process.env.DOPPLER_SECRETS_JSON).DIRECT_DB_CONNECTION_STRING)")
        
        if [ -z "$$DIRECT_DB_CONNECTION_STRING" ]; then
           echo "❌ Error: DIRECT_DB_CONNECTION_STRING not found in secrets."
           exit 1
        fi

        # Run migration using npx (finds globally installed package)
        npx --yes supabase db push --db-url "$$DIRECT_DB_CONNECTION_STRING"
    
    secretEnv: ['DOPPLER_SECRETS_JSON']

  # -------------------------------------------------------------------------
  # 2. Build and Push (Kaniko)
  # -------------------------------------------------------------------------
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://./backend'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:${_VERSION}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--build-arg=PRODUCTION=true'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--cache-repo=gcr.io/${_PROJECT_ID}/cache'

# Secrets Configuration
availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/doppler-hit8-prod/versions/latest
    env: 'DOPPLER_SECRETS_JSON'

options:
  logging: CLOUD_LOGGING_ONLY
