steps:
  # Database Migration
  - name: 'ghcr.io/supabase/cli:latest'
    id: 'db-migration'
    args:
      - 'db'
      - 'push'
      - '--db-url'
      - '$$DIRECT_DB_CONNECTION_STRING'
    secretEnv: ['DIRECT_DB_CONNECTION_STRING']

  # Build and Push Docker Image
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://./backend'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:${_VERSION}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--build-arg=PRODUCTION=true'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--cache-repo=gcr.io/${_PROJECT_ID}/cache'
    # Kaniko pushes images directly, so no need for images: section

# Secrets Configuration
availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/DIRECT_DB_CONNECTION_STRING/versions/latest
    env: 'DIRECT_DB_CONNECTION_STRING'

options:
  logging: CLOUD_LOGGING_ONLY

