steps:
  # -------------------------------------------------------------------------
  # 1. Database Migration (Install CLI on the fly)
  # -------------------------------------------------------------------------
  - name: 'node:20-bullseye-slim'  # Use a standard, reliable Node image
    id: 'db-migration'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Installing Supabase CLI..."
        # Install via NPM (Official distribution method)
        npm install -g supabase
        
        echo "🚀 Starting Supabase Migration..."
        if [ ! -d "supabase/migrations" ]; then
           echo "⚠️  No 'supabase/migrations' folder found. Skipping."
           exit 0
        fi

        # Run migration
        # The 'npx' or global 'supabase' command works here
        supabase db push --db-url "$$DIRECT_DB_CONNECTION_STRING"
    
    secretEnv: ['DIRECT_DB_CONNECTION_STRING']

  # -------------------------------------------------------------------------
  # 2. Build and Push (Kaniko) - Unchanged
  # -------------------------------------------------------------------------
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-image'
    waitFor: ['db-migration']
    args:
      - '--dockerfile=Dockerfile'
      # ... (rest of your build args)
      - '--cache=true'
