steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=Dockerfile.prod'
      - '--context=dir://.'
      - '--destination=${_IMAGE_NAME}:${_TAG}'
      - '--destination=${_IMAGE_NAME}:latest'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--cache-repo=gcr.io/${_PROJECT_ID}/cache'
images:
  - '${_IMAGE_NAME}:${_TAG}'
  - '${_IMAGE_NAME}:latest'
options:
  machineType: 'E2_STANDARD_2'  # Entry-level: 2 vCPUs, 8GB RAM (cost-effective)
  logging: CLOUD_LOGGING_ONLY

