steps:
  - name: 'alpine:latest'
    entrypoint: 'sh'
    env:
      # REPLACE THIS WITH YOUR PROXY VM IP
      - 'PROXY_URL=http://10.0.0.2:3128'
    args:
      - '-c'
      - |
        echo "⚙️ Configuring Proxy..."
        export http_proxy=$$PROXY_URL
        export https_proxy=$$PROXY_URL

        echo "⚙️ Installing tools (via Proxy)..."
        # Alpine uses the environment variables automatically
        apk add --no-cache curl

        echo "---------------------------------------------------"
        echo "🔍 1. IP CHECK (Should be your Static IP)"
        # This request goes: Container -> Proxy VM -> NAT -> Static IP -> Internet
        curl -s https://api.ipify.org || echo "❌ Failed to reach Internet"
        echo ""

        echo "---------------------------------------------------"
        echo "🔍 2. DATABASE CHECK"
        DB_HOST="db.dxwwmmhfhsljkhftnzke.supabase.co"
        DB_PORT="5432"
        
        echo "Testing TCP to $$DB_HOST:$$DB_PORT..."
        # curl -v telnet:// uses the proxy for the CONNECT handshake
        curl -v --proxy $$PROXY_URL telnet://$$DB_HOST:$$DB_PORT

options:
  pool:
    name: 'projects/hit8-poc/locations/europe-west1/workerPools/private-pool-1'
