name: Deploy Backend
description: Deploy backend to GCP or Scaleway

inputs:
  cloud:
    description: 'Cloud provider (gcp or scw)'
    required: true
  environment:
    description: 'Environment (staging or production)'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
  gcp_sa_key:
    description: 'GCP Service Account Key'
    required: false
  gcp_project_id:
    description: 'GCP Project ID'
    required: false
  scw_access_key:
    description: 'Scaleway Access Key'
    required: false
  scw_secret_key:
    description: 'Scaleway Secret Key'
    required: false
  scw_project_id:
    description: 'Scaleway Project ID'
    required: false
  scw_organization_id:
    description: 'Scaleway Organization ID'
    required: false

runs:
  using: composite
  steps:
    # GCP Deployment
    - name: Setup gcloud
      if: inputs.cloud == 'gcp'
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to GCP
      if: inputs.cloud == 'gcp'
      shell: bash
      env:
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        set -e
        printf '%s' "$GCP_SA_KEY" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        IMAGE="europe-west1-docker.pkg.dev/${GCP_PROJECT_ID}/backend/api:${{ inputs.image_tag }}"

        gcloud run services update "hit8-api${ENV_SUFFIX}" \
          --image "$IMAGE" \
          --region europe-west1 \
          --project "$GCP_PROJECT_ID" \
          --quiet

        gcloud run jobs update "hit8-report-job${ENV_SUFFIX}" \
          --image "$IMAGE" \
          --region europe-west1 \
          --project "$GCP_PROJECT_ID" \
          --quiet

    - name: Health Check (GCP)
      if: inputs.cloud == 'gcp'
      shell: bash
      run: |
        set -e
        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        URL="https://api${ENV_SUFFIX}.hit8.io/health"
        echo "Waiting 30s for deployment..."
        sleep 30
        for i in 1 2 3 4 5; do
          if curl -f -s "$URL" > /dev/null; then
            echo "✅ Health check passed: $URL"
            exit 0
          fi
          echo "Attempt $i/5 failed, retrying..."
          sleep 10
        done
        echo "❌ Health check failed after 5 attempts"
        exit 1

    # Scaleway Deployment
    - name: Deploy to Scaleway
      if: inputs.cloud == 'scw'
      shell: bash
      env:
        SCW_ACCESS_KEY: ${{ inputs.scw_access_key }}
        SCW_SECRET_KEY: ${{ inputs.scw_secret_key }}
        SCW_DEFAULT_PROJECT_ID: ${{ inputs.scw_project_id }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ inputs.scw_organization_id }}
      run: |
        set -e
        # Install script writes directly to /usr/local/bin/scw
        curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh

        mkdir -p ~/.config/scw
        touch ~/.config/scw/config.yaml
        scw config set access-key="$SCW_ACCESS_KEY"
        scw config set secret-key="$SCW_SECRET_KEY"
        scw config set default-project-id="$SCW_DEFAULT_PROJECT_ID"
        scw config set default-organization-id="$SCW_DEFAULT_ORGANIZATION_ID"
        scw config set default-region="fr-par"

        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        CONTAINER_JSON=$(scw container container list name="hit8-api${ENV_SUFFIX}" -o json)
        CONTAINER_ID=$(echo "$CONTAINER_JSON" | jq -r '.[0].id')
        if [ "$CONTAINER_ID" = "null" ] || [ -z "$CONTAINER_ID" ]; then
          echo "❌ ERROR: No container found with name=hit8-api${ENV_SUFFIX}"
          echo "Available containers:"
          scw container container list -o json | jq -r '.[].name' || true
          exit 1
        fi

        scw container container update "$CONTAINER_ID" \
          registry-image="rg.fr-par.scw.cloud/hit8-registry/api:${{ inputs.image_tag }}" \
          redeploy=true

    - name: Health Check (Scaleway)
      if: inputs.cloud == 'scw'
      shell: bash
      run: |
        set -e
        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        URL="https://scw${ENV_SUFFIX}.hit8.io/health"
        echo "Waiting 30s for deployment..."
        sleep 30
        for i in 1 2 3 4 5; do
          if curl -f -s "$URL" > /dev/null; then
            echo "✅ Health check passed: $URL"
            exit 0
          fi
          echo "Attempt $i/5 failed, retrying..."
          sleep 10
        done
        echo "❌ Health check failed after 5 attempts"
        exit 1
