name: Deploy Backend
description: Deploy backend to GCP or Scaleway

inputs:
  cloud:
    description: 'Cloud provider (gcp or scw)'
    required: true
  environment:
    description: 'Environment (staging or production)'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
  gcp_sa_key:
    description: 'GCP Service Account Key'
    required: false
  gcp_project_id:
    description: 'GCP Project ID'
    required: false
  scw_access_key:
    description: 'Scaleway Access Key'
    required: false
  scw_secret_key:
    description: 'Scaleway Secret Key'
    required: false
  scw_project_id:
    description: 'Scaleway Project ID'
    required: false
  scw_organization_id:
    description: 'Scaleway Organization ID'
    required: false

runs:
  using: composite
  steps:
    # GCP Deployment
    - name: Setup gcloud
      if: inputs.cloud == 'gcp'
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to GCP
      if: inputs.cloud == 'gcp'
      shell: bash
      env:
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        set -e
        printf '%s' "$GCP_SA_KEY" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        IMAGE="europe-west1-docker.pkg.dev/${GCP_PROJECT_ID}/backend/api:${{ inputs.image_tag }}"

        gcloud run services update "hit8-api${ENV_SUFFIX}" \
          --image "$IMAGE" \
          --region europe-west1 \
          --project "$GCP_PROJECT_ID" \
          --quiet

        gcloud run jobs update "hit8-report-job${ENV_SUFFIX}" \
          --image "$IMAGE" \
          --region europe-west1 \
          --project "$GCP_PROJECT_ID" \
          --quiet

    - name: Health Check (GCP)
      if: inputs.cloud == 'gcp'
      shell: bash
      env:
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        set -e
        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        printf '%s' "$GCP_SA_KEY" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json --quiet
        SERVICE_URL=$(gcloud run services describe "hit8-api${ENV_SUFFIX}" --region europe-west1 --project "$GCP_PROJECT_ID" --format='value(status.url)')
        URL="${SERVICE_URL%/}/health"
        echo "Health check URL: $URL"
        echo "Waiting 60s for deployment..."
        sleep 60
        for i in 1 2 3 4 5 6 7 8; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 10 --max-time 15 "$URL" || echo "000")
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Health check passed: $URL"
            exit 0
          fi
          echo "Attempt $i/8: HTTP $HTTP_CODE"
          sleep 10
        done
        echo "❌ Health check failed after 8 attempts"
        exit 1

    # Scaleway Deployment
    - name: Deploy to Scaleway
      if: inputs.cloud == 'scw'
      shell: bash
      env:
        SCW_ACCESS_KEY: ${{ inputs.scw_access_key }}
        SCW_SECRET_KEY: ${{ inputs.scw_secret_key }}
        SCW_DEFAULT_PROJECT_ID: ${{ inputs.scw_project_id }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ inputs.scw_organization_id }}
      run: |
        set -e
        # Install script writes directly to /usr/local/bin/scw
        curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh

        mkdir -p ~/.config/scw
        touch ~/.config/scw/config.yaml
        scw config set access-key="$SCW_ACCESS_KEY"
        scw config set secret-key="$SCW_SECRET_KEY"
        scw config set default-project-id="$SCW_DEFAULT_PROJECT_ID"
        scw config set default-organization-id="$SCW_DEFAULT_ORGANIZATION_ID"
        scw config set default-region="fr-par"

        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        
        # Verify Doppler token secret exists and has a version
        SECRET_NAME="doppler-token${ENV_SUFFIX}"
        SECRET_JSON=$(scw secret secret list name="$SECRET_NAME" -o json || echo "[]")
        SECRET_ID=$(echo "$SECRET_JSON" | jq -r '.[0].id // empty')
        if [ -z "$SECRET_ID" ] || [ "$SECRET_ID" = "null" ]; then
          echo "❌ ERROR: Secret '$SECRET_NAME' not found"
          echo "Available secrets:"
          scw secret secret list -o json | jq -r '.[].name' || true
          exit 1
        fi
        
        SECRET_VERSIONS=$(scw secret version list secret-id="$SECRET_ID" -o json || echo "[]")
        VERSION_COUNT=$(echo "$SECRET_VERSIONS" | jq 'length')
        if [ "$VERSION_COUNT" -eq 0 ]; then
          echo "⚠️  WARNING: Secret '$SECRET_NAME' exists but has no versions"
          echo "The container will fail to start. Add a version with:"
          echo "  scw secret secret add-version $SECRET_ID data=\"\$(echo -n '<doppler-token>' | base64)\""
          echo ""
          echo "Continuing deployment anyway (will fail health check)..."
        else
          echo "✅ Secret '$SECRET_NAME' has $VERSION_COUNT version(s)"
        fi
        
        CONTAINER_JSON=$(scw container container list name="hit8-api${ENV_SUFFIX}" -o json)
        CONTAINER_ID=$(echo "$CONTAINER_JSON" | jq -r '.[0].id')
        if [ "$CONTAINER_ID" = "null" ] || [ -z "$CONTAINER_ID" ]; then
          echo "❌ ERROR: No container found with name=hit8-api${ENV_SUFFIX}"
          echo "Available containers:"
          scw container container list -o json | jq -r '.[].name' || true
          exit 1
        fi

        scw container container update "$CONTAINER_ID" \
          registry-image="rg.fr-par.scw.cloud/hit8-registry/api:${{ inputs.image_tag }}" \
          redeploy=true

    - name: Health Check (Scaleway)
      if: inputs.cloud == 'scw'
      shell: bash
      env:
        SCW_ACCESS_KEY: ${{ inputs.scw_access_key }}
        SCW_SECRET_KEY: ${{ inputs.scw_secret_key }}
        SCW_DEFAULT_PROJECT_ID: ${{ inputs.scw_project_id }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ inputs.scw_organization_id }}
      run: |
        set -e
        ENV_SUFFIX=${{ inputs.environment == 'production' && '-prd' || '-stg' }}
        # Use container default domain (no dependency on custom DNS scw-stg.hit8.io)
        CONTAINER_JSON=$(scw container container list name="hit8-api${ENV_SUFFIX}" -o json)
        CONTAINER_ID=$(echo "$CONTAINER_JSON" | jq -r '.[0].id')
        CONTAINER_DETAIL=$(scw container container get "$CONTAINER_ID" -o json)
        DOMAIN=$(echo "$CONTAINER_DETAIL" | jq -r '.domain_name')
        STATUS=$(echo "$CONTAINER_DETAIL" | jq -r '.status')
        echo "Container Status: $STATUS"
        echo "Container Domain: $DOMAIN"
        URL="https://${DOMAIN}/health"
        echo "Health check URL: $URL"
        echo "Waiting 30s for deployment (cold start can be slow when MinScale=0)..."
        sleep 30
        MAX_ATTEMPTS=3
        for i in $(seq 1 $MAX_ATTEMPTS); do
          # Try health endpoint
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Health check passed: $URL (HTTP $HTTP_CODE)"
            exit 0
          fi
          # If 404, try other paths to diagnose
          if [ "$HTTP_CODE" = "404" ]; then
            ROOT_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://${DOMAIN}/" || echo "000")
            DOCS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://${DOMAIN}/docs" || echo "000")
            VERSION_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://${DOMAIN}/version" || echo "000")
            echo "Attempt $i/$MAX_ATTEMPTS: /health=$HTTP_CODE, /=${ROOT_CODE}, /docs=${DOCS_CODE}, /version=${VERSION_CODE}"
            # If we get 200 on any path, app is running but /health route might be wrong
            if [ "$ROOT_CODE" = "200" ] || [ "$DOCS_CODE" = "200" ] || [ "$VERSION_CODE" = "200" ]; then
              echo "⚠️ App is responding but /health returns 404 - checking route registration"
            fi
          else
            echo "Attempt $i/$MAX_ATTEMPTS failed (HTTP $HTTP_CODE), retrying in 10s..."
          fi
          if [ $i -lt $MAX_ATTEMPTS ]; then
            sleep 10
          fi
        done
        echo "❌ Health check failed after $MAX_ATTEMPTS attempts"
        echo "Final container status:"
        scw container container get "$CONTAINER_ID" -o json | jq '{status, domain_name, registry_image, port}'
        exit 1
